### ISSUE TITLE
Projet Maintainers and contributors

### ISSUE THREAD

**Issue by abe-101** [Schrodinger-Hat/community#11]
It may be a nice idea to split the `author` section in the README's of our project to `Maintainers` and `contributors`

## Maintainers
- Community members who have taken upon themselves to oversee the project
## Contributors
- All individuals who have contributed to the project

What are your thoughts?

**Comment by abe-101** [comment]
I brought up the idea for https://github.com/Schrodinger-Hat/youtube-to-anchorfm/issues/45 but it can be applied to all our projects

**Comment by Wabri** [comment]
is a tricky issue because active members are called contributors, so using that name to refer to coders who have contributed might seem wrong.

Changing the community name for active members to maintainers might be the solution, but that requires a discussion on the internal server with all contributors.

Or maybe we can just give a damn and move on as you propose.

**Comment by abe-101** [comment]
Another approach is to have a section in the readme called:
# Credits

**Comment by Wabri** [comment]
@abe-101 can we close this issue? I think contributors of a project could be external (as external contributors) and internal (as sh contributors), what do you think?
